/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as LogRouteImport } from './routes/log'
import { Route as IdeasRouteImport } from './routes/ideas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LogIndexRouteImport } from './routes/log.index'
import { Route as LogSlugRouteImport } from './routes/log.$slug'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const LogRoute = LogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasRoute = IdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogIndexRoute = LogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LogRoute,
} as any)
const LogSlugRoute = LogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ideas': typeof IdeasRoute
  '/log': typeof LogRouteWithChildren
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/log/$slug': typeof LogSlugRoute
  '/log/': typeof LogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ideas': typeof IdeasRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/log/$slug': typeof LogSlugRoute
  '/log': typeof LogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ideas': typeof IdeasRoute
  '/log': typeof LogRouteWithChildren
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/log/$slug': typeof LogSlugRoute
  '/log/': typeof LogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ideas'
    | '/log'
    | '/review'
    | '/settings'
    | '/log/$slug'
    | '/log/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ideas' | '/review' | '/settings' | '/log/$slug' | '/log'
  id:
    | '__root__'
    | '/'
    | '/ideas'
    | '/log'
    | '/review'
    | '/settings'
    | '/log/$slug'
    | '/log/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IdeasRoute: typeof IdeasRoute
  LogRoute: typeof LogRouteWithChildren
  ReviewRoute: typeof ReviewRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas': {
      id: '/ideas'
      path: '/ideas'
      fullPath: '/ideas'
      preLoaderRoute: typeof IdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log/': {
      id: '/log/'
      path: '/'
      fullPath: '/log/'
      preLoaderRoute: typeof LogIndexRouteImport
      parentRoute: typeof LogRoute
    }
    '/log/$slug': {
      id: '/log/$slug'
      path: '/$slug'
      fullPath: '/log/$slug'
      preLoaderRoute: typeof LogSlugRouteImport
      parentRoute: typeof LogRoute
    }
  }
}

interface LogRouteChildren {
  LogSlugRoute: typeof LogSlugRoute
  LogIndexRoute: typeof LogIndexRoute
}

const LogRouteChildren: LogRouteChildren = {
  LogSlugRoute: LogSlugRoute,
  LogIndexRoute: LogIndexRoute,
}

const LogRouteWithChildren = LogRoute._addFileChildren(LogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IdeasRoute: IdeasRoute,
  LogRoute: LogRouteWithChildren,
  ReviewRoute: ReviewRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
